//! Build script: generates the Tauri context and one `allow-<command>` ACL permission per
//! webview command, which `capabilities/default.json` grants to the main window.
//!
//! `AppManifest::commands` would write generated permission files into the source tree
//! (`src-tauri/permissions/autogenerated`). The same TOML is written into `OUT_DIR` instead and
//! registered through `permissions_path_pattern`, so builds leave the candidate tree unchanged.

use std::fmt::Write as _;
use std::path::PathBuf;

/// Every command the webview may invoke. Keep in sync with `commands::COMMAND_NAMES` (a unit test
/// asserts equality) and with `capabilities/default.json`.
const COMMANDS: &[&str] = &[
    "store_status",
    "choose_legacy_root",
    "dry_run_import",
    "import_legacy_root",
    "read_dashboard_documents",
    "set_item_completion",
    "set_discussion_field",
    "resolve_pending_source_link",
    "set_manual_grade",
    "read_avatar_bytes",
    "open_library_resource",
    "copy_assignment_text",
    "list_snapshots",
    "restore_snapshot",
    "export_legacy_folder",
    "set_canvas_refresh_enabled",
    "start_canvas_refresh",
    "prepare_store_promotion",
    "confirm_store_promotion",
    "demote_store_for_rollback",
    "export_frozen_for_rollback",
];

fn main() {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"))
        .join("../dist/public/asset-manifest.json");
    println!("cargo:rerun-if-changed={}", manifest.display());
    let manifest_bytes = std::fs::read(&manifest).unwrap_or_else(|_| {
        panic!(
            "frontend asset manifest is missing at {}; run `node scripts/build-tauri.mjs --prepare-only` first",
            manifest.display()
        )
    });
    if manifest_bytes.is_empty() {
        panic!("frontend asset manifest is empty");
    }

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let permissions_dir = out_dir.join("app-command-permissions");
    std::fs::create_dir_all(&permissions_dir).expect("create permission output folder");
    for command in COMMANDS {
        let slug = command.replace('_', "-");
        let mut toml = String::from("# Generated by build.rs.\n\n[[permission]]\n");
        writeln!(toml, "identifier = \"allow-{slug}\"").expect("format");
        writeln!(toml, "description = \"Enables the {command} command.\"").expect("format");
        writeln!(toml, "commands.allow = [\"{command}\"]").expect("format");
        std::fs::write(permissions_dir.join(format!("{command}.toml")), toml)
            .expect("write command permission");
    }
    let pattern: &'static str =
        Box::leak(format!("{}/*.toml", permissions_dir.display()).into_boxed_str());
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().permissions_path_pattern(pattern)),
    )
    .expect("failed to run the Tauri build script");

    // The generated manifest is included in `frontendDist` and in bundle resources. Copying it
    // to OUT_DIR makes Cargo track the exact bytes alongside the generated Tauri context.
    let embedded_manifest = out_dir.join("frontend-asset-manifest.json");
    std::fs::write(&embedded_manifest, &manifest_bytes)
        .expect("copy frontend asset manifest into build output");

    // Put a literal feature marker in each macOS executable. The release verifier can then test
    // the actual app and bundled helper bytes rather than trusting the build command's flags.
    if std::env::var("CARGO_CFG_TARGET_OS").ok().as_deref() == Some("macos") {
        let marker_path = out_dir.join("duegood-build-feature-marker");
        let marker = if std::env::var_os("CARGO_FEATURE_TEST_OVERRIDES").is_some() {
            b"duegood-feature:test-overrides".as_slice()
        } else {
            b"duegood-feature:release".as_slice()
        };
        std::fs::write(&marker_path, marker).expect("write executable build marker");
        println!("cargo:rerun-if-env-changed=CARGO_FEATURE_TEST_OVERRIDES");
        for binary in ["duegood-desktop", "duegood-refresh"] {
            println!("cargo:rustc-link-arg-bin={binary}=-sectcreate");
            println!("cargo:rustc-link-arg-bin={binary}=__TEXT");
            println!("cargo:rustc-link-arg-bin={binary}=__duegood");
            println!(
                "cargo:rustc-link-arg-bin={binary}={}",
                marker_path.display()
            );
        }
        for argument in [
            "-sectcreate",
            "__TEXT",
            "__dgassets",
            embedded_manifest
                .to_str()
                .expect("asset manifest output path is UTF-8"),
        ] {
            println!("cargo:rustc-link-arg-bin=duegood-desktop={argument}");
        }
    }
}
