-- Institution-scoped identity: an account is the (institution, Canvas user id) pair, not the
-- Canvas user id alone, so the same id at two institutions is never treated as one account.
CREATE TABLE accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  institution_origin TEXT NOT NULL,
  canvas_user_id TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  UNIQUE (institution_origin, canvas_user_id)
);

-- A connection holds one account's encrypted Canvas credentials. `id` is generated by the
-- application (a UUID) before insert, not left to AUTOINCREMENT, because the credential
-- envelope's associated data binds to this id and must exist before the row does. `generation`
-- is a fencing counter: it increments on revoke, so a caller holding a generation captured
-- earlier can detect it's stale without a second round trip. A row can only be deleted once
-- revoked (enforced in src/db/repository.ts, not here), mirroring the "revoke with the
-- provider, then delete" order in docs/01-SETUP.md. `key_version` is its own indexed column,
-- not buried in the envelope, so retiring a key version can be checked with a query instead of
-- decrypting every row.
CREATE TABLE connections (
  id TEXT PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  generation INTEGER NOT NULL DEFAULT 1,
  key_version INTEGER NOT NULL,
  encrypted_access_token TEXT NOT NULL,
  encrypted_refresh_token TEXT,
  access_token_expires_at INTEGER,
  created_at INTEGER NOT NULL,
  revoked_at INTEGER
);

CREATE INDEX connections_account_id_idx ON connections (account_id);
CREATE INDEX connections_key_version_idx ON connections (key_version);

-- A session is looked up only by `token_hash` (SHA-256 of the opaque bearer token issued to the
-- browser) — the raw token is never stored, so a leaked DB row can't be replayed as a cookie.
-- `id` is a separate UUID so future tables (e.g. CSRF binding in a later slice) can reference a
-- session without ever handling its secret hash. Both `absolute_expires_at` and
-- `idle_expires_at` are enforced (src/auth/session.ts, not here): the absolute bound caps a
-- session's total lifetime regardless of activity; the idle bound ends it after inactivity.
CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  token_hash TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  absolute_expires_at INTEGER NOT NULL,
  idle_expires_at INTEGER NOT NULL,
  revoked_at INTEGER
);

CREATE UNIQUE INDEX sessions_token_hash_idx ON sessions (token_hash);
CREATE INDEX sessions_account_id_idx ON sessions (account_id);

-- A pre-identity record of one in-flight OAuth authorization attempt. No `account_id` — this
-- exists before any account is known to exist. `state_hash` and `binding_hash` are SHA-256 of
-- the random `state` value and the browser-bound secret respectively; like `sessions.token_hash`,
-- the raw values are never stored, only handed back once to the caller (src/auth/oauth-state.ts).
-- `consumed_at` makes the callback one-time-use: it's set by a single atomic
-- `UPDATE ... WHERE consumed_at IS NULL RETURNING ...`, so two concurrent callbacks racing the
-- same state can't both succeed. `institution_origin` and `redirect_uri` are checked again at
-- consume time against what the callback presents, so a state minted for one institution or
-- redirect can't be replayed against another.
CREATE TABLE oauth_states (
  id TEXT PRIMARY KEY,
  state_hash TEXT NOT NULL,
  binding_hash TEXT NOT NULL,
  institution_origin TEXT NOT NULL,
  redirect_uri TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  consumed_at INTEGER
);

CREATE UNIQUE INDEX oauth_states_state_hash_idx ON oauth_states (state_hash);
