-- Institution-scoped identity: an account is the (institution, Canvas user id) pair, not the
-- Canvas user id alone, so the same id at two institutions is never treated as one account.
CREATE TABLE accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  institution_origin TEXT NOT NULL,
  canvas_user_id TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  UNIQUE (institution_origin, canvas_user_id)
);

-- A connection holds one account's encrypted Canvas credentials. `id` is generated by the
-- application (a UUID) before insert, not left to AUTOINCREMENT, because the credential
-- envelope's associated data binds to this id and must exist before the row does. `generation`
-- is a fencing counter: it increments on revoke, so a caller holding a generation captured
-- earlier can detect it's stale without a second round trip. A row can only be deleted once
-- revoked (enforced in src/db/repository.ts, not here), mirroring the "revoke with the
-- provider, then delete" order in docs/01-SETUP.md. `key_version` is its own indexed column,
-- not buried in the envelope, so retiring a key version can be checked with a query instead of
-- decrypting every row.
CREATE TABLE connections (
  id TEXT PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  generation INTEGER NOT NULL DEFAULT 1,
  key_version INTEGER NOT NULL,
  encrypted_access_token TEXT NOT NULL,
  encrypted_refresh_token TEXT,
  access_token_expires_at INTEGER,
  created_at INTEGER NOT NULL,
  revoked_at INTEGER
);

CREATE INDEX connections_account_id_idx ON connections (account_id);
CREATE INDEX connections_key_version_idx ON connections (key_version);
