import type { Account, Connection, ConnectionStatus, Course } from "./types";

interface AccountRow {
  readonly id: number;
  readonly institution_origin: string;
  readonly canvas_user_id: string;
  readonly created_at: number;
}

function toAccount(row: AccountRow): Account {
  return {
    id: row.id,
    institutionOrigin: row.institution_origin,
    canvasUserId: row.canvas_user_id,
    createdAt: row.created_at,
  };
}

interface ConnectionRow {
  readonly id: string;
  readonly account_id: number;
  readonly status: ConnectionStatus;
  readonly generation: number;
  readonly key_version: number;
  readonly encrypted_access_token: string;
  readonly encrypted_refresh_token: string | null;
  readonly access_token_expires_at: number | null;
  readonly created_at: number;
  readonly revoked_at: number | null;
}

function toConnection(row: ConnectionRow): Connection {
  return {
    id: row.id,
    accountId: row.account_id,
    status: row.status,
    generation: row.generation,
    keyVersion: row.key_version,
    encryptedAccessToken: row.encrypted_access_token,
    encryptedRefreshToken: row.encrypted_refresh_token,
    accessTokenExpiresAt: row.access_token_expires_at,
    createdAt: row.created_at,
    revokedAt: row.revoked_at,
  };
}

const CONNECTION_COLUMNS =
  "id, account_id, status, generation, key_version, encrypted_access_token, encrypted_refresh_token, access_token_expires_at, created_at, revoked_at";

/**
 * Finds the account for this institution + Canvas user id, creating it on first sighting.
 * The composite key means the same Canvas user id at a different institution is always a
 * distinct account, never a collision. Never takes a caller-supplied account id — identity is
 * derived only from the institution/Canvas-user-id pair a caller has already verified.
 */
export async function findOrCreateAccount(
  db: D1Database,
  institutionOrigin: string,
  canvasUserId: string,
  now: number,
): Promise<Account> {
  const inserted = await db
    .prepare(
      `INSERT INTO accounts (institution_origin, canvas_user_id, created_at)
       VALUES (?1, ?2, ?3)
       ON CONFLICT (institution_origin, canvas_user_id) DO NOTHING
       RETURNING id, institution_origin, canvas_user_id, created_at`,
    )
    .bind(institutionOrigin, canvasUserId, now)
    .first<AccountRow>();
  if (inserted) return toAccount(inserted);

  const existing = await db
    .prepare(
      `SELECT id, institution_origin, canvas_user_id, created_at
       FROM accounts
       WHERE institution_origin = ?1 AND canvas_user_id = ?2`,
    )
    .bind(institutionOrigin, canvasUserId)
    .first<AccountRow>();
  if (!existing) throw new Error("account lookup failed after insert conflict");
  return toAccount(existing);
}

export async function getAccountById(db: D1Database, accountId: number): Promise<Account | undefined> {
  const row = await db
    .prepare(`SELECT id, institution_origin, canvas_user_id, created_at FROM accounts WHERE id = ?1`)
    .bind(accountId)
    .first<AccountRow>();
  return row ? toAccount(row) : undefined;
}

interface CourseRow {
  readonly id: string;
  readonly account_id: number;
  readonly canvas_course_id: string;
  readonly course_code: string | null;
  readonly title: string | null;
  readonly term: string | null;
  readonly snapshot_generation: number;
  readonly import_lease_token: string | null;
  readonly import_lease_expires_at: number | null;
  readonly last_successful_check_at: number | null;
  readonly created_at: number;
}

function toCourse(row: CourseRow): Course {
  return {
    id: row.id,
    accountId: row.account_id,
    canvasCourseId: row.canvas_course_id,
    courseCode: row.course_code,
    title: row.title,
    term: row.term,
    snapshotGeneration: row.snapshot_generation,
    importLeaseToken: row.import_lease_token,
    importLeaseExpiresAt: row.import_lease_expires_at,
    lastSuccessfulCheckAt: row.last_successful_check_at,
    createdAt: row.created_at,
  };
}

const COURSE_COLUMNS =
  "id, account_id, canvas_course_id, course_code, title, term, snapshot_generation, import_lease_token, import_lease_expires_at, last_successful_check_at, created_at";

export interface CreateCourseInput {
  /** Generated by the caller (e.g. `crypto.randomUUID()`) before insert, so `source_items` can
   * reference it in the same request that creates it. */
  readonly id: string;
  readonly accountId: number;
  readonly canvasCourseId: string;
  readonly courseCode: string | null;
  readonly title: string | null;
  readonly term: string | null;
  readonly now: number;
}

/**
 * Creates the (account, Canvas course) row on first selection, or returns the existing one — the
 * composite unique index means a caller can never accidentally create two rows for the same
 * course. Never takes a caller-supplied snapshot generation or lease: both start unset, exactly as
 * migration defaults leave them.
 */
export async function findOrCreateCourse(db: D1Database, input: CreateCourseInput): Promise<Course> {
  const inserted = await db
    .prepare(
      `INSERT INTO courses (id, account_id, canvas_course_id, course_code, title, term, created_at)
       VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
       ON CONFLICT (account_id, canvas_course_id) DO NOTHING
       RETURNING ${COURSE_COLUMNS}`,
    )
    .bind(input.id, input.accountId, input.canvasCourseId, input.courseCode, input.title, input.term, input.now)
    .first<CourseRow>();
  if (inserted) return toCourse(inserted);

  const existing = await db
    .prepare(`SELECT ${COURSE_COLUMNS} FROM courses WHERE account_id = ?1 AND canvas_course_id = ?2`)
    .bind(input.accountId, input.canvasCourseId)
    .first<CourseRow>();
  if (!existing) throw new Error("course lookup failed after insert conflict");
  return toCourse(existing);
}

export async function getCourseById(db: D1Database, courseId: string): Promise<Course | undefined> {
  const row = await db.prepare(`SELECT ${COURSE_COLUMNS} FROM courses WHERE id = ?1`).bind(courseId).first<CourseRow>();
  return row ? toCourse(row) : undefined;
}

export interface CommittedSourceItem {
  readonly canvasItemId: string;
  readonly fingerprint: string;
  readonly available: boolean;
}

interface SourceItemRow {
  readonly canvas_item_id: string;
  readonly fingerprint: string;
  readonly available: number;
}

/** Every source item ever committed for this course, available or not — the "last known inventory"
 * `compareInventory` diffs a fresh fetch against, and the same read a fresh course's feasibility
 * estimate is drawn from (see `src/import/course-import.ts`). */
export async function listSourceItems(db: D1Database, courseId: string): Promise<CommittedSourceItem[]> {
  const result = await db
    .prepare(`SELECT canvas_item_id, fingerprint, available FROM source_items WHERE course_id = ?1`)
    .bind(courseId)
    .all<SourceItemRow>();
  return result.results.map((row) => ({
    canvasItemId: row.canvas_item_id,
    fingerprint: row.fingerprint,
    available: row.available === 1,
  }));
}

export interface CreateConnectionInput {
  /** Generated by the caller (e.g. `crypto.randomUUID()`) before the credential is encrypted, so
   * the connection id is available for the encryption envelope's associated data ahead of insert. */
  readonly id: string;
  readonly accountId: number;
  readonly keyVersion: number;
  readonly encryptedAccessToken: string;
  readonly encryptedRefreshToken: string | null;
  readonly accessTokenExpiresAt: number | null;
  readonly now: number;
}

export async function createConnection(db: D1Database, input: CreateConnectionInput): Promise<Connection> {
  const row = await db
    .prepare(
      `INSERT INTO connections
         (id, account_id, status, generation, key_version, encrypted_access_token, encrypted_refresh_token, access_token_expires_at, created_at)
       VALUES (?1, ?2, 'active', 1, ?3, ?4, ?5, ?6, ?7)
       RETURNING ${CONNECTION_COLUMNS}`,
    )
    .bind(
      input.id,
      input.accountId,
      input.keyVersion,
      input.encryptedAccessToken,
      input.encryptedRefreshToken,
      input.accessTokenExpiresAt,
      input.now,
    )
    .first<ConnectionRow>();
  if (!row) throw new Error("connection insert returned no row");
  return toConnection(row);
}

/** Returns the connection only while it's active; a revoked or deleted connection reads as
 * absent, which is what callers checking the fence (see below) want. */
export async function getActiveConnection(db: D1Database, connectionId: string): Promise<Connection | undefined> {
  const row = await db
    .prepare(`SELECT ${CONNECTION_COLUMNS} FROM connections WHERE id = ?1 AND status = 'active'`)
    .bind(connectionId)
    .first<ConnectionRow>();
  return row ? toConnection(row) : undefined;
}

/** Throws unless the connection is still active at exactly the generation the caller captured
 * earlier — rejecting both a revoked/removed connection and a stale generation (revoked, then
 * reconnected) in one check, without a caller needing to compare fields itself. */
export async function assertConnectionFence(
  db: D1Database,
  connectionId: string,
  expectedGeneration: number,
): Promise<void> {
  const connection = await getActiveConnection(db, connectionId);
  if (!connection) throw new Error("connection is not active");
  if (connection.generation !== expectedGeneration) throw new Error("connection generation is stale");
}

/**
 * Marks an active connection revoked and bumps its fencing generation. Requires the connection
 * to currently be active — revoking an already-revoked or missing connection throws — so
 * `revokedAt`/the generation bump only ever happen once per revoke, matching the
 * "revoke with the provider, then delete" order the credential lifecycle depends on.
 */
export async function revokeConnection(db: D1Database, connectionId: string, now: number): Promise<Connection> {
  const row = await db
    .prepare(
      `UPDATE connections
       SET status = 'revoked', generation = generation + 1, revoked_at = ?2
       WHERE id = ?1 AND status = 'active'
       RETURNING ${CONNECTION_COLUMNS}`,
    )
    .bind(connectionId, now)
    .first<ConnectionRow>();
  if (!row) throw new Error("connection not found or already revoked");
  return toConnection(row);
}

/** Deletes a connection's row, permanently discarding its encrypted credential. Only a revoked
 * connection can be deleted — a caller can never skip straight from active to gone, which is the
 * ordering `revocation-order.test.ts` locks in. */
export async function deleteConnection(db: D1Database, connectionId: string): Promise<void> {
  const result = await db.prepare(`DELETE FROM connections WHERE id = ?1 AND status = 'revoked'`).bind(connectionId).run();
  if (result.meta.changes === 0) throw new Error("connection not found or not yet revoked");
}

/** Every connection an account owns, active or revoked. Route handlers project this down to a
 * credential-free summary before returning it to a caller — this function itself still returns
 * the full row (including the encrypted envelope) because it's also the right shape for internal
 * callers that need it, e.g. re-encrypting on refresh. */
export async function getConnectionsForAccount(db: D1Database, accountId: number): Promise<Connection[]> {
  const result = await db
    .prepare(`SELECT ${CONNECTION_COLUMNS} FROM connections WHERE account_id = ?1 ORDER BY created_at ASC`)
    .bind(accountId)
    .all<ConnectionRow>();
  return result.results.map(toConnection);
}

export interface RefreshedCredentials {
  readonly keyVersion: number;
  readonly encryptedAccessToken: string;
  readonly encryptedRefreshToken: string | null;
  readonly accessTokenExpiresAt: number | null;
}

/** Persists a re-encrypted credential after a token refresh. Folds the connection fence into the
 * same atomic statement as the write (`status = 'active' AND generation = ?`), so a connection
 * revoked between the caller's fence check and this write can never have its envelope silently
 * resurrected — the same TOCTOU concern `revokeConnection`'s single-statement update guards
 * against. */
export async function updateConnectionCredentials(
  db: D1Database,
  connectionId: string,
  expectedGeneration: number,
  credentials: RefreshedCredentials,
): Promise<Connection> {
  const row = await db
    .prepare(
      `UPDATE connections
       SET key_version = ?3, encrypted_access_token = ?4, encrypted_refresh_token = ?5, access_token_expires_at = ?6
       WHERE id = ?1 AND status = 'active' AND generation = ?2
       RETURNING ${CONNECTION_COLUMNS}`,
    )
    .bind(
      connectionId,
      expectedGeneration,
      credentials.keyVersion,
      credentials.encryptedAccessToken,
      credentials.encryptedRefreshToken,
      credentials.accessTokenExpiresAt,
    )
    .first<ConnectionRow>();
  if (!row) throw new Error("connection is not active");
  return toConnection(row);
}

/** True when no connection row (active or revoked-but-not-yet-deleted) still references this key
 * version — i.e. it's safe to drop the key from the ring's legacy map. A revoked connection still
 * counts until its row is actually deleted, since its stored envelope is still encrypted under
 * that version until then. */
export async function isKeyVersionRetirable(db: D1Database, keyVersion: number): Promise<boolean> {
  const row = await db.prepare(`SELECT 1 FROM connections WHERE key_version = ?1 LIMIT 1`).bind(keyVersion).first();
  return row === null;
}
