/** Source-neutral, local-only observation merge contract. No network or parser lives here. */
type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };
type JsonObject = Record<string, unknown>;

const MAX_PENDING_LINKS = 100;
const MAX_PENDING_CANDIDATES = 20;
const MAX_FIELD_SOURCES = 20;
const RESERVED_FIELDS = new Set([
  "id", "course", "canvasId", "done", "doneAt", "notes", "discussionPostDone", "discussionRepliesDone",
  "manualGradeObservation", "source", "sourceReferences", "fieldObservations",
]);
const SOURCE_FIELDS = new Set([
  "kind", "title", "at", "points", "detail", "url", "submissionStatus", "grade", "score",
  "submittedAt", "gradedAt", "assignmentGroupId", "assignmentGroupName", "assignmentGroupWeight",
]);
const SOURCE_PRIORITY: Readonly<Record<SourceReference["source"], number>> = {
  ical: 1, canvas: 2, pdf: 0, manual: 0,
};


export interface SourceReference {
  readonly institution: string;
  readonly course: string;
  readonly source: "canvas" | "ical" | "manual" | "pdf";
  readonly id: string;
  readonly instance?: string;
}

/** One source-owned set of facts for an immutable local item ID. */
export interface SourceObservation {
  readonly localId: string;
  readonly course: string;
  readonly reference: SourceReference;
  readonly fields: Readonly<Record<string, JsonValue>>;
  /** Source-provided fact time, when known. Never generated by the merger. */
  readonly observedAt?: string;
  /** Explicitly verified aliases for the same source item; no title or date matching is performed. */
  readonly verifiedReferences?: readonly SourceReference[];
  /** Unverified candidates are held for review and never auto-merged. */
  readonly possibleLocalIds?: readonly string[];
}

export interface PendingSourceLink {
  /** Stable, scoped identifier safe to expose only to the local dashboard. */
  readonly id: string;
  /** The suppressed source item's immutable prospective local ID. */
  readonly localId: string;
  readonly course: string;
  readonly reference: SourceReference;
  readonly verifiedReferences: readonly SourceReference[];
  readonly fields: Readonly<Record<string, JsonValue>>;
  readonly observedAt?: string;
  readonly candidateIds: readonly string[];
  readonly reason: "ambiguous-match" | "conflicting-match";
  /** Older holds lack replayable facts and become actionable after the next source observation. */
  readonly needsRefresh?: true;
}

export interface AcquisitionResult {
  readonly changed: boolean;
  readonly added: number;
  readonly updated: number;
  readonly backfilled: number;
  readonly held: readonly PendingSourceLink[];
}

function object(value: unknown, label: string): JsonObject {
  if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${label} must be an object`);
  return value as JsonObject;
}

function text(value: unknown, label: string, max = 160): string {
  if (typeof value !== "string" || value.length === 0 || value.length > max) throw new Error(`${label} must be a nonempty string up to ${max} characters`);
  return value;
}

function reference(value: unknown, label: string): SourceReference {
  const candidate = object(value, label);
  const source = candidate.source;
  if (source !== "canvas" && source !== "ical" && source !== "manual" && source !== "pdf") throw new Error(`${label}.source is unsupported`);
  const instance = candidate.instance === undefined ? undefined : text(candidate.instance, `${label}.instance`);
  return {
    institution: text(candidate.institution, `${label}.institution`),
    course: text(candidate.course, `${label}.course`),
    source,
    id: text(candidate.id, `${label}.id`),
    ...(instance === undefined ? {} : { instance }),
  };
}

function sourceReferenceKey(value: SourceReference): string {
  return JSON.stringify([value.institution, value.course, value.source, value.id, value.instance ?? null]);
}

/** The scoped reference is the pending record's stable identity; titles and dates never participate. */
function pendingLinkId(value: SourceReference): string { return sourceReferenceKey(value); }

function jsonValue(value: unknown): value is JsonValue {
  if (value === null || typeof value === "boolean" || typeof value === "string") return true;
  if (typeof value === "number") return Number.isFinite(value);
  if (Array.isArray(value)) return value.every(jsonValue);
  return typeof value === "object" && value !== null && Object.values(value).every(jsonValue);
}

function equal(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function itemReferences(item: JsonObject, label: string): SourceReference[] {
  if (item.sourceReferences === undefined) return [];
  if (!Array.isArray(item.sourceReferences)) throw new Error(`${label}.sourceReferences must be an array`);
  return item.sourceReferences.map((value, index) => reference(value, `${label}.sourceReferences[${index}]`));
}

function allItems(document: JsonObject): JsonObject[] {
  const active = Array.isArray(document.items) ? document.items : [];
  const archived = Array.isArray(document.archivedForecastItems) ? document.archivedForecastItems : [];
  return [...active, ...archived].map((value, index) => object(value, `coursework item ${index}`));
}

/** Reject globally duplicated scoped references before a source can silently claim two local items. */
export function validateSourceReferences(document: JsonObject): void {
  const owners = new Map<string, string>();
  for (const [index, item] of allItems(document).entries()) {
    const id = text(item.id, `coursework item ${index}.id`);
    for (const value of itemReferences(item, `coursework item ${id}`)) {
      const key = sourceReferenceKey(value);
      const owner = owners.get(key);
      if (owner !== undefined) throw new Error(`duplicate scoped source reference for ${owner} and ${id}`);
      owners.set(key, id);
    }
  }
}

function checkedFields(value: Readonly<Record<string, JsonValue>>): readonly [string, JsonValue][] {
  return Object.entries(value).map(([field, fieldValue]) => {
    if (!/^[A-Za-z][A-Za-z0-9]{0,79}$/.test(field)) throw new Error(`invalid observed field: ${field}`);
    if (RESERVED_FIELDS.has(field)) throw new Error(`observations may not write local field: ${field}`);
    if (!SOURCE_FIELDS.has(field)) throw new Error(`field is not declared source-owned: ${field}`);
    if (!jsonValue(fieldValue)) throw new Error(`observed field ${field} is not JSON`);
    return [field, fieldValue];
  });
}

interface FieldFact {
  readonly owner: SourceReference;
  readonly value: JsonValue;
  readonly observedAt?: string;
}

function observedAt(value: unknown, label: string): string | undefined {
  if (value === undefined) return undefined;
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?Z$/.test(value) || !Number.isFinite(Date.parse(value))) {
    throw new Error(`${label} must be a UTC timestamp`);
  }
  return value;
}

function stableFact(incoming: FieldFact, previous: FieldFact | undefined): FieldFact {
  if (previous === undefined || !equal(previous.value, incoming.value)) return incoming;
  return { owner: incoming.owner, value: incoming.value, ...(previous.observedAt === undefined ? {} : { observedAt: previous.observedAt }) };
}

function fieldFacts(value: unknown, label: string): { selected: FieldFact; alternatives: FieldFact[] } | null {
  if (value === undefined) return null;
  const current = object(value, label);
  const selected = { owner: reference(current.owner, `${label}.owner`), value: current.value as JsonValue,
    ...(observedAt(current.observedAt, `${label}.observedAt`) === undefined ? {} : { observedAt: current.observedAt as string }) };
  if (!jsonValue(selected.value)) throw new Error(`${label}.value is not JSON`);
  const alternatives = current.alternatives === undefined ? [] : current.alternatives;
  if (!Array.isArray(alternatives)) throw new Error(`${label}.alternatives must be an array`);
  const parsed = alternatives.map((candidate, index) => {
    const entry = object(candidate, `${label}.alternatives[${index}]`);
    const fact = { owner: reference(entry.owner, `${label}.alternatives[${index}].owner`), value: entry.value as JsonValue,
      ...(observedAt(entry.observedAt, `${label}.alternatives[${index}].observedAt`) === undefined ? {} : { observedAt: entry.observedAt as string }) };
    if (!jsonValue(fact.value)) throw new Error(`${label}.alternatives[${index}].value is not JSON`);
    return fact;
  });
  const keys = [selected, ...parsed].map((fact) => sourceReferenceKey(fact.owner));
  if (new Set(keys).size !== keys.length || keys.length > MAX_FIELD_SOURCES) throw new Error(`${label} has duplicate or excessive source facts`);
  return { selected, alternatives: parsed };
}

/** A changed iCal due date wins over a legacy value; an explicitly fresher API fact can retake it. */
function shouldPromote(field: string, selected: FieldFact, candidate: FieldFact, incoming: FieldFact): boolean {
  if (field !== "at") return SOURCE_PRIORITY[incoming.owner.source] > SOURCE_PRIORITY[selected.owner.source];
  const selectedTime = selected.observedAt === undefined ? null : Date.parse(selected.observedAt);
  if (incoming.owner.source === "ical" && selected.owner.source === "canvas") {
    const candidateTime = candidate.observedAt === undefined ? null : Date.parse(candidate.observedAt);
    return candidateTime !== null && (selectedTime === null || candidateTime > selectedTime);
  }
  if (incoming.owner.source === "canvas" && selected.owner.source === "ical") {
    const apiTime = incoming.observedAt === undefined ? null : Date.parse(incoming.observedAt);
    return apiTime !== null && (selectedTime === null || apiTime >= selectedTime);
  }
  return SOURCE_PRIORITY[incoming.owner.source] > SOURCE_PRIORITY[selected.owner.source];
}

function mergeFieldFact(item: JsonObject, ownership: JsonObject, field: string, incoming: FieldFact): { changed: boolean; visibleChanged: boolean } {
  const old = fieldFacts(ownership[field], `item ${String(item.id)}.fieldObservations.${field}`);
  const canvas = itemReferences(item, `item ${String(item.id)}`).find((entry) => entry.source === "canvas");
  // Existing Canvas facts have no per-field provenance yet. Preserve their displayed value when
  // the first lower-priority iCal observation is linked to that legacy item.
  const selected: FieldFact = old?.selected ?? (canvas !== undefined && item[field] !== undefined && incoming.owner.source === "ical"
    ? { owner: canvas, value: item[field] as JsonValue }
    : incoming);
  if (!jsonValue(selected.value)) throw new Error(`item ${String(item.id)}.${field} is not JSON`);
  const alternatives = [...(old?.alternatives ?? [])];
  const incomingKey = sourceReferenceKey(incoming.owner);
  const selectedKey = sourceReferenceKey(selected.owner);
  let nextSelected = selected;
  if (incomingKey === selectedKey) {
    // A fresh API capture can establish recency even when Canvas reports the same due date.
    // Repeated iCal windows keep their earlier timestamp until the value changes.
    nextSelected = field === "at" && incoming.owner.source === "canvas" && incoming.observedAt !== undefined
      ? incoming : stableFact(incoming, selected);
  }
  else {
    const existingIndex = alternatives.findIndex((fact) => sourceReferenceKey(fact.owner) === incomingKey);
    if (existingIndex >= 0) alternatives[existingIndex] = stableFact(incoming, alternatives[existingIndex]);
    else alternatives.push(incoming);
    const candidate = existingIndex >= 0 ? alternatives[existingIndex]! : incoming;
    if (shouldPromote(field, selected, candidate, incoming)) {
      // A fresh API capture explicitly confirms its due date, even if its value matches an
      // older alternative. Repeat iCal imports retain the earlier fact time when unchanged.
      nextSelected = field === "at" && incoming.owner.source === "canvas" ? incoming : candidate;
      alternatives.splice(alternatives.findIndex((fact) => sourceReferenceKey(fact.owner) === incomingKey), 1);
      const previousIndex = alternatives.findIndex((fact) => sourceReferenceKey(fact.owner) === selectedKey);
      if (previousIndex >= 0) alternatives[previousIndex] = selected;
      else alternatives.push(selected);
    }
  }
  if (alternatives.length + 1 > MAX_FIELD_SOURCES) throw new Error(`item ${String(item.id)}.${field} has too many source facts`);
  const next = { ...nextSelected, ...(alternatives.length === 0 ? {} : { alternatives }) };
  const visibleChanged = !equal(item[field], nextSelected.value);
  if (visibleChanged) item[field] = nextSelected.value;
  const changed = !equal(ownership[field], next);
  if (changed) ownership[field] = next;
  return { changed, visibleChanged };
}

function writeReferences(item: JsonObject, additions: readonly SourceReference[]): boolean {
  const current = itemReferences(item, `coursework item ${String(item.id)}`);
  const known = new Set(current.map(sourceReferenceKey));
  const next = [...current];
  for (const addition of additions) {
    const key = sourceReferenceKey(addition);
    if (known.has(key)) continue;
    next.push(addition);
    known.add(key);
  }
  if (equal(current, next)) return false;
  item.sourceReferences = next;
  return true;
}

function addPendingLink(document: JsonObject, held: PendingSourceLink): boolean {
  const current = document.pendingSourceLinks === undefined ? [] : document.pendingSourceLinks;
  if (!Array.isArray(current)) throw new Error("pendingSourceLinks must be an array");
  const normalized = { id: held.id, localId: held.localId, course: held.course, reference: held.reference,
    verifiedReferences: [...held.verifiedReferences], fields: held.fields,
    ...(held.observedAt === undefined ? {} : { observedAt: held.observedAt }),
    candidateIds: [...held.candidateIds], reason: held.reason };
  const existingIndex = current.findIndex((entry) => {
    const record = object(entry, "pendingSourceLinks entry");
    return record.id === held.id || (record.id === undefined && pendingLinkId(reference(record.reference, "pendingSourceLinks entry.reference")) === held.id);
  });
  if (existingIndex >= 0) {
    if (equal(current[existingIndex], normalized)) return false;
    document.pendingSourceLinks = [...current.slice(0, existingIndex), normalized, ...current.slice(existingIndex + 1)];
    return true;
  }
  if (current.length >= MAX_PENDING_LINKS) throw new Error("pending source link limit reached");
  document.pendingSourceLinks = [...current, normalized];
  return true;
}

function pendingLinkFrom(value: unknown, label: string): PendingSourceLink {
  const entry = object(value, label);
  const referenceValue = reference(entry.reference, `${label}.reference`);
  if (entry.id === undefined) {
    const candidateIds = entry.candidateIds;
    if (!Array.isArray(candidateIds) || candidateIds.length > MAX_PENDING_CANDIDATES) throw new Error(`${label}.candidateIds must be a bounded array`);
    const normalizedCandidates = candidateIds.map((candidate, index) => text(candidate, `${label}.candidateIds[${index}]`)).sort();
    if (new Set(normalizedCandidates).size !== normalizedCandidates.length) throw new Error(`${label}.candidateIds must be unique`);
    if (entry.reason !== "ambiguous-match" && entry.reason !== "conflicting-match") throw new Error(`${label}.reason is unsupported`);
    return { id: pendingLinkId(referenceValue), localId: "", course: referenceValue.course,
      reference: referenceValue, verifiedReferences: [], fields: {}, candidateIds: normalizedCandidates,
      reason: entry.reason, needsRefresh: true };
  }
  const id = text(entry.id, `${label}.id`, 1_000);
  if (id !== pendingLinkId(referenceValue)) throw new Error(`${label}.id does not match its scoped reference`);
  const localId = text(entry.localId, `${label}.localId`);
  const course = text(entry.course, `${label}.course`);
  if (referenceValue.course !== course) throw new Error(`${label}.course does not match its reference`);
  const verifiedReferences = entry.verifiedReferences === undefined ? [] : arrayOfReferences(entry.verifiedReferences, `${label}.verifiedReferences`);
  const fieldsValue = object(entry.fields, `${label}.fields`);
  const fields: Record<string, JsonValue> = {};
  for (const [field, fieldValue] of checkedFields(fieldsValue as Readonly<Record<string, JsonValue>>)) fields[field] = fieldValue;
  const candidateIds = entry.candidateIds;
  if (!Array.isArray(candidateIds) || candidateIds.length > MAX_PENDING_CANDIDATES) throw new Error(`${label}.candidateIds must be a bounded array`);
  const normalizedCandidates = candidateIds.map((candidate, index) => text(candidate, `${label}.candidateIds[${index}]`)).sort();
  if (new Set(normalizedCandidates).size !== normalizedCandidates.length) throw new Error(`${label}.candidateIds must be unique`);
  const reason = entry.reason;
  if (reason !== "ambiguous-match" && reason !== "conflicting-match") throw new Error(`${label}.reason is unsupported`);
  const at = observedAt(entry.observedAt, `${label}.observedAt`);
  return { id, localId, course, reference: referenceValue, verifiedReferences, fields,
    ...(at === undefined ? {} : { observedAt: at }), candidateIds: normalizedCandidates, reason };
}

function arrayOfReferences(value: unknown, label: string): readonly SourceReference[] {
  if (!Array.isArray(value)) throw new Error(`${label} must be an array`);
  return value.map((candidate, index) => reference(candidate, `${label}[${index}]`));
}

/** Exposes older holds as refresh-required and prevents them from becoming invisible or replayable. */
export function pendingSourceLinks(document: JsonObject): readonly PendingSourceLink[] {
  if (document.pendingSourceLinks === undefined) return [];
  if (!Array.isArray(document.pendingSourceLinks)) throw new Error("pendingSourceLinks must be an array");
  const complete = document.pendingSourceLinks.map((entry, index) => pendingLinkFrom(entry, `pendingSourceLinks[${index}]`));
  if (new Set(complete.map((entry) => entry.id)).size !== complete.length || complete.length > MAX_PENDING_LINKS) throw new Error("pending source links have duplicate or excessive identities");
  return complete;
}

/** Deterministically adds Canvas references to legacy records without changing their local IDs. */
function backfillCanvasReferences(document: JsonObject, institution: string): number {
  const scope = text(institution, "institution");
  validateSourceReferences(document);
  let added = 0;
  for (const item of allItems(document)) {
    if ((typeof item.canvasId !== "string" && typeof item.canvasId !== "number") || String(item.canvasId).length === 0) continue;
    const course = text(item.course, `coursework item ${String(item.id)}.course`);
    if (writeReferences(item, [{ institution: scope, course, source: "canvas", id: String(item.canvasId) }])) added += 1;
  }
  validateSourceReferences(document);
  return added;
}

/**
 * Applies only declared source-owned fields. Matching is exact by immutable local ID or a verified
 * scoped reference; potential cross-source matches are durable pending links rather than guesses.
 */
export function applySourceObservations(document: JsonObject, institution: string, observations: readonly SourceObservation[]): AcquisitionResult {
  const backfilled = backfillCanvasReferences(document, institution);
  const unresolvedByReference = new Map(pendingSourceLinks(document).map((link) => [link.id, link]));
  if (!Array.isArray(document.courses)) throw new Error("courses must be an array");
  const courseKeys = new Set(document.courses.map((value, index) => text(object(value, `courses[${index}]`).key, `courses[${index}].key`)));
  const active = Array.isArray(document.items) ? document.items.map((value, index) => object(value, `items[${index}]`)) : (() => { throw new Error("items must be an array"); })();
  const byId = new Map<string, JsonObject>();
  for (const item of allItems(document)) {
    const id = text(item.id, "item.id");
    if (byId.has(id)) throw new Error(`duplicate immutable item id: ${id}`);
    byId.set(id, item);
  }
  const byReference = new Map<string, JsonObject>();
  for (const item of allItems(document)) for (const value of itemReferences(item, `coursework item ${String(item.id)}`)) byReference.set(sourceReferenceKey(value), item);

  const seenIncoming = new Set<string>();
  let added = 0;
  let updated = 0;
  let changed = backfilled > 0;
  const held: PendingSourceLink[] = [];
  const ordered = [...observations].sort((left, right) => `${left.localId}\u0000${sourceReferenceKey(left.reference)}`.localeCompare(`${right.localId}\u0000${sourceReferenceKey(right.reference)}`));
  for (const observation of ordered) {
    const localId = text(observation.localId, "observation.localId");
    const course = text(observation.course, "observation.course");
    if (!courseKeys.has(course)) throw new Error("observation course is unknown");
    const primary = reference(observation.reference, "observation.reference");
    if (primary.source === "manual" || primary.source === "pdf") throw new Error("manual and PDF grade observations require the later grade policy");
    const factTime = observedAt(observation.observedAt, "observation.observedAt");
    if (primary.institution !== institution || primary.course !== course) throw new Error("observation scope must match institution and course");
    const aliases = (observation.verifiedReferences ?? []).map((value, index) => reference(value, `observation.verifiedReferences[${index}]`));
    if (aliases.some((value) => value.institution !== institution || value.course !== course)) throw new Error("verified reference scope must match observation");
    const references = [primary, ...aliases];
    for (const value of references) {
      const key = sourceReferenceKey(value);
      if (seenIncoming.has(key)) throw new Error("duplicate scoped source reference in observation batch");
      seenIncoming.add(key);
    }
    const fields = checkedFields(observation.fields);
    const verified = new Set<JsonObject>();
    const localMatch = byId.get(localId);
    if (localMatch !== undefined) verified.add(localMatch);
    for (const value of references) {
      const match = byReference.get(sourceReferenceKey(value));
      if (match !== undefined) verified.add(match);
    }
    const possibleInput = observation.possibleLocalIds ?? [];
    if (possibleInput.length > MAX_PENDING_CANDIDATES) throw new Error("too many possible local IDs");
    const possible = [...new Set(possibleInput.map((id) => text(id, "possibleLocalId")))].filter((id) => byId.has(id)).sort();
    const existingPending = unresolvedByReference.get(pendingLinkId(primary));
    if (existingPending !== undefined) {
      // An unresolved scoped reference is a durable stop sign. Refresh its observed facts even
      // when the newest fuzzy pass finds fewer (or no) candidates; it must never create an API
      // item or auto-link by title/date while the user is still deciding.
      const candidateIds = [...new Set([...verified].map((item) => text(item.id, "item.id")).concat(possible))].sort();
      if (candidateIds.length > MAX_PENDING_CANDIDATES) throw new Error("too many possible local IDs");
      const pending: PendingSourceLink = { id: existingPending.id, localId, course, reference: primary, verifiedReferences: aliases,
        fields: Object.fromEntries(fields), ...(factTime === undefined ? {} : { observedAt: factTime }), candidateIds,
        reason: verified.size > 1 || (verified.size === 1 && possible.some((id) => byId.get(id) !== [...verified][0])) ? "conflicting-match" : existingPending.reason };
      held.push(pending);
      changed = addPendingLink(document, pending) || changed;
      continue;
    }
    if (verified.size > 1 || (verified.size === 1 && possible.some((id) => byId.get(id) !== [...verified][0]))) {
      const candidateIds = [...new Set([...verified].map((item) => text(item.id, "item.id")).concat(possible))].sort();
      const pending: PendingSourceLink = { id: pendingLinkId(primary), localId, course, reference: primary, verifiedReferences: aliases,
        fields: Object.fromEntries(fields), ...(factTime === undefined ? {} : { observedAt: factTime }), candidateIds, reason: "conflicting-match" };
      held.push(pending);
      changed = addPendingLink(document, pending) || changed;
      continue;
    }
    if (verified.size === 0 && possible.length > 0) {
      const pending: PendingSourceLink = { id: pendingLinkId(primary), localId, course, reference: primary, verifiedReferences: aliases,
        fields: Object.fromEntries(fields), ...(factTime === undefined ? {} : { observedAt: factTime }), candidateIds: possible, reason: "ambiguous-match" };
      held.push(pending);
      changed = addPendingLink(document, pending) || changed;
      continue;
    }
    let item = [...verified][0];
    if (item === undefined) {
      item = { id: localId, course, source: primary.source };
      active.push(item);
      document.items = active;
      byId.set(localId, item);
      added += 1;
      changed = true;
    } else if (item.course !== course) {
      throw new Error(`immutable item ${localId} belongs to a different course`);
    }
    if (writeReferences(item, references)) changed = true;
    const ownership = item.fieldObservations === undefined ? {} : object(item.fieldObservations, `item ${localId}.fieldObservations`);
    for (const [field, fieldValue] of fields) {
      const merged = mergeFieldFact(item, ownership, field, { owner: primary, value: fieldValue, ...(factTime === undefined ? {} : { observedAt: factTime }) });
      if (merged.visibleChanged) updated += 1;
      if (merged.changed || merged.visibleChanged) changed = true;
    }
    if (Object.keys(ownership).length > 0) item.fieldObservations = ownership;
    for (const value of references) byReference.set(sourceReferenceKey(value), item);
  }
  validateSourceReferences(document);
  return { changed, added, updated, backfilled, held };
}

export type PendingLinkDecision = "confirm" | "reject";

/**
 * Resolves one reviewed candidate. A confirmation replays its exact API observation against the
 * selected immutable local item; rejection materializes the separately identified source item.
 * Neither path has title/date matching, and the caller supplies an exact document-version fence.
 */
export function resolvePendingSourceLink(document: JsonObject, institution: string, pendingId: string, localItemId: string, decision: PendingLinkDecision): AcquisitionResult {
  const links = pendingSourceLinks(document);
  const pending = links.find((entry) => entry.id === pendingId);
  if (pending === undefined) throw new Error("pending source link changed; reload and retry");
  if (pending.needsRefresh) throw new Error("pending source link needs a fresh source observation before review");
  const items = allItems(document);
  if (decision !== "confirm" && decision !== "reject") throw new Error("pending source link decision is unsupported");
  const linkedItem = (candidate: SourceReference): JsonObject | undefined => {
    const key = sourceReferenceKey(candidate);
    return items.find((item) => itemReferences(item, `coursework item ${String(item.id)}`).some((existing) => sourceReferenceKey(existing) === key));
  };
  if (decision === "confirm") {
    if (!pending.candidateIds.includes(localItemId)) throw new Error("pending source link candidate changed; reload and retry");
    const existing = items.find((item) => item.id === localItemId);
    if (existing === undefined || existing.course !== pending.course) throw new Error("pending source link candidate changed; reload and retry");
    if ([pending.reference, ...pending.verifiedReferences].some((candidate) => {
      const linked = linkedItem(candidate);
      return linked !== undefined && linked.id !== localItemId;
    })) throw new Error("pending source link conflicts with existing provenance; keep it pending");
  }
  if (decision === "reject" && items.some((item) => item.id === pending.localId)) throw new Error("pending source link changed; reload and retry");
  if (decision === "reject" && linkedItem(pending.reference) !== undefined) throw new Error("pending source link conflicts with existing provenance; keep it pending");
  const observation: SourceObservation = {
    localId: decision === "confirm" ? localItemId : pending.localId,
    course: pending.course,
    reference: pending.reference,
    // A keep-distinct decision must not inherit an alias already owned by another local item.
    // Unclaimed verified aliases remain with the new source item as provenance.
    verifiedReferences: decision === "confirm" ? pending.verifiedReferences : pending.verifiedReferences.filter((candidate) => linkedItem(candidate) === undefined),
    fields: pending.fields,
    ...(pending.observedAt === undefined ? {} : { observedAt: pending.observedAt }),
  };
  // Temporarily remove this hold before replaying its exact observation. The acquisition gate
  // otherwise correctly suppresses every unresolved reference, including this explicit choice.
  const current = document.pendingSourceLinks as unknown[];
  document.pendingSourceLinks = current.filter((entry) => object(entry, "pendingSourceLinks entry").id !== pendingId);
  const result = applySourceObservations(document, institution, [observation]);
  if (result.held.length !== 0) throw new Error("pending source link changed; reload and retry");
  return { ...result, changed: true };
}
