//! Rotating, private store snapshots and conservative recovery.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use serde::Serialize;
use serde_json::Value;

use crate::config::{MANIFEST_FILE, REPLACE_JOURNAL_FILE, STAGING_PREFIX};
use crate::export::copy_tree;
use crate::export::ExportProgress;
use crate::store::{
    atomic_write, create_private_dir, fsync_dir, node_json_bytes, utc_stamp, Store, StoreCondition,
    StoreError, StoreState,
};

/// Maximum number of daily and pre-refresh snapshots retained together.
pub const MAX_SNAPSHOTS: usize = 14;

/// One available recovery point; its identifier is generated by Rust, never a path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SnapshotInfo {
    pub id: String,
    pub created_at: String,
    pub kind: &'static str,
}

fn root(store: &Store) -> PathBuf {
    store.data_root().join("snapshots")
}

fn snapshots(store: &Store) -> Result<Vec<SnapshotInfo>, StoreError> {
    let directory = root(store);
    match fs::symlink_metadata(&directory) {
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(error.into()),
        Ok(metadata) if !metadata.file_type().is_dir() => {
            return Err(StoreError::Invalid(
                "snapshots folder is not a plain directory",
            ))
        }
        Ok(_) => {}
    }
    let mut list = Vec::new();
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().to_string();
        if !entry.file_type()?.is_dir() || !valid_id(&name) {
            continue;
        }
        let kind = if name.starts_with("daily-") {
            "daily"
        } else {
            "pre-refresh"
        };
        let compact = name.split('-').nth(1).unwrap_or("");
        let created_at = format!(
            "{}-{}-{}T{}:{}:{}Z",
            &compact[0..4],
            &compact[4..6],
            &compact[6..8],
            &compact[9..11],
            &compact[11..13],
            &compact[13..15]
        );
        list.push(SnapshotInfo {
            id: name,
            created_at,
            kind,
        });
    }
    list.sort_by(|a, b| {
        b.created_at
            .cmp(&a.created_at)
            .then_with(|| b.id.cmp(&a.id))
    });
    Ok(list)
}

fn valid_id(id: &str) -> bool {
    let prefix = id.starts_with("daily-") || id.starts_with("refresh-");
    let mut parts = id.split('-');
    let _ = parts.next();
    let stamp = parts.next().unwrap_or("");
    let suffix = parts.next().unwrap_or("");
    prefix
        && parts.next().is_none()
        && stamp.len() == 16
        && stamp.as_bytes()[8] == b'T'
        && stamp.ends_with('Z')
        && stamp
            .bytes()
            .enumerate()
            .all(|(i, c)| i == 8 || i == 15 || c.is_ascii_digit())
        && suffix.len() == 8
        && suffix.bytes().all(|c| c.is_ascii_hexdigit())
}

/// Lists newest snapshots first without exposing a filesystem path.
pub fn list_snapshots(store: &Store) -> Result<Vec<SnapshotInfo>, StoreError> {
    let _snapshot_lock = store.snapshot_lock()?;
    snapshots(store)
}

fn take(
    store: &Store,
    kind: &str,
    now: SystemTime,
    progress: &mut dyn FnMut(ExportProgress),
) -> Result<Option<SnapshotInfo>, StoreError> {
    let _snapshot_lock = store.snapshot_lock()?;
    let _read_lock = store.read_lock()?;
    take_locked(store, kind, now, progress)
}

/// Snapshot implementation for callers that already hold a shared or exclusive store lock.
fn take_locked(
    store: &Store,
    kind: &str,
    now: SystemTime,
    progress: &mut dyn FnMut(ExportProgress),
) -> Result<Option<SnapshotInfo>, StoreError> {
    if !matches!(store.condition()?, StoreCondition::Ready(_)) {
        return Ok(None);
    }
    let existing = snapshots(store)?;
    let stamp = utc_stamp(now);
    if kind == "daily"
        && existing.iter().any(|entry| {
            entry
                .id
                .starts_with(&format!("daily-{}", &stamp.compact[..8]))
        })
    {
        return Ok(None);
    }
    let directory = root(store);
    create_private_dir(&directory, true)?;
    let id = format!(
        "{kind}-{}-{}",
        stamp.compact,
        &uuid::Uuid::new_v4().simple().to_string()[..8]
    );
    let target = directory.join(&id);
    let result = copy_tree(&store.store_dir(), &target, true, progress);
    if result.is_err() {
        let _ = fs::remove_dir_all(&target);
    }
    result?;
    fsync_dir(&directory)?;
    let mut all = snapshots(store)?;
    all.sort_by(|a, b| {
        a.created_at
            .cmp(&b.created_at)
            .then_with(|| a.id.cmp(&b.id))
    });
    while all.len() > MAX_SNAPSHOTS {
        let oldest = all.remove(0);
        fs::remove_dir_all(directory.join(oldest.id))?;
    }
    fsync_dir(&directory)?;
    Ok(Some(SnapshotInfo {
        id,
        created_at: stamp.iso,
        kind: if kind == "daily" {
            "daily"
        } else {
            "pre-refresh"
        },
    }))
}

/// Takes at most one daily snapshot on the first open of a ready store each UTC day.
pub fn snapshot_daily(store: &Store, now: SystemTime) -> Result<Option<SnapshotInfo>, StoreError> {
    snapshot_daily_with_progress(store, now, &mut |_| {})
}

/// Takes a daily snapshot and reports only copied file and byte counts.
pub fn snapshot_daily_with_progress(
    store: &Store,
    now: SystemTime,
    progress: &mut dyn FnMut(ExportProgress),
) -> Result<Option<SnapshotInfo>, StoreError> {
    take(store, "daily", now, progress)
}

/// Phase 3 hook. The reason is Rust-only and never becomes a path or webview argument.
pub fn snapshot_before_refresh(store: &Store, reason: &str) -> Result<SnapshotInfo, StoreError> {
    if reason.is_empty() || reason.len() > 80 {
        return Err(StoreError::Invalid("invalid snapshot reason"));
    }
    let _snapshot_lock = store.snapshot_lock()?;
    let _read_lock = store.read_lock()?;
    snapshot_before_refresh_locked(store, reason)
}

/// Takes a pre-refresh snapshot when the caller already holds a stable store read or write lock.
pub(crate) fn snapshot_before_refresh_locked(
    store: &Store,
    reason: &str,
) -> Result<SnapshotInfo, StoreError> {
    snapshot_before_refresh_locked_with_progress(store, reason, &mut |_| {})
}

/// Snapshot variant for callers that already hold a stable store read or write lock and need bounded
/// file/byte counts while the copy runs.
pub(crate) fn snapshot_before_refresh_locked_with_progress(
    store: &Store,
    reason: &str,
    progress: &mut dyn FnMut(ExportProgress),
) -> Result<SnapshotInfo, StoreError> {
    if reason.is_empty() || reason.len() > 80 {
        return Err(StoreError::Invalid("invalid snapshot reason"));
    }
    take_locked(store, "refresh", SystemTime::now(), progress)?
        .ok_or(StoreError::Invalid("no store to snapshot"))
}

fn manifest_state(path: &Path) -> Result<StoreState, StoreError> {
    let bytes = fs::read(path.join(MANIFEST_FILE))?;
    let value: Value = serde_json::from_slice(&bytes)
        .map_err(|_| StoreError::Invalid("snapshot manifest is malformed"))?;
    match value.get("state").and_then(Value::as_str) {
        Some("preview") => Ok(StoreState::Preview),
        Some("authoritative") => Ok(StoreState::Authoritative),
        _ => Err(StoreError::Invalid("snapshot state is unknown")),
    }
}

/// Restores only one of this store's own snapshots. The current store is first moved into the
/// never-deleted backups folder using the same journal recovery path as preview replacement.
pub fn restore_snapshot(store: &Store, id: &str) -> Result<(), StoreError> {
    if !valid_id(id) {
        return Err(StoreError::Invalid("unknown snapshot"));
    }
    let _snapshot_lock = store.snapshot_lock()?;
    let _lock = store.write_lock()?;
    let current = match store.condition()? {
        StoreCondition::Ready(summary) => Some(summary.state),
        StoreCondition::Damaged(_) => None,
        StoreCondition::Empty => return Err(StoreError::Invalid("there is no store to archive")),
    };
    let source = root(store).join(id);
    if !fs::symlink_metadata(&source)?.file_type().is_dir() {
        return Err(StoreError::Invalid("unknown snapshot"));
    }
    let snapshot_state = manifest_state(&source)?;
    if current.is_some_and(|state| state != snapshot_state) {
        return Err(StoreError::Invalid(
            "snapshot belongs to a different store state",
        ));
    }
    let staging = store.data_root().join(format!(
        "{STAGING_PREFIX}restore-{}",
        uuid::Uuid::new_v4().simple()
    ));
    let copied = copy_tree(&source, &staging, true, &mut |_| {});
    if copied.is_err() {
        let _ = fs::remove_dir_all(&staging);
    }
    copied?;
    let backups = store.backups_dir();
    if fs::symlink_metadata(&backups).is_ok_and(|metadata| !metadata.file_type().is_dir()) {
        return Err(StoreError::Invalid(
            "backups folder is not a plain directory",
        ));
    }
    create_private_dir(&backups, true)?;
    let archive = format!(
        "store-{}-{}",
        utc_stamp(SystemTime::now()).compact,
        &uuid::Uuid::new_v4().simple().to_string()[..8]
    );
    let journal = store.data_root().join(REPLACE_JOURNAL_FILE);
    atomic_write(
        &journal,
        &node_json_bytes(&serde_json::json!({ "archive": archive })),
    )?;
    let current_path = store.store_dir();
    fs::rename(&current_path, backups.join(&archive))?;
    fsync_dir(&backups)?;
    fsync_dir(store.data_root())?;
    if let Err(error) = fs::rename(&staging, &current_path) {
        fs::rename(backups.join(&archive), &current_path)?;
        fs::remove_file(&journal)?;
        return Err(error.into());
    }
    fsync_dir(store.data_root())?;
    fs::remove_file(journal)?;
    fsync_dir(store.data_root())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::{new_preview_manifest, node_json_bytes};
    use crate::testutil::{assert_private_tree, TempRoot};
    use std::time::{Duration, UNIX_EPOCH};

    #[test]
    fn daily_dedup_rotation_and_restore_archive() {
        let temp = TempRoot::new("snapshots");
        let store = Store::open(temp.path(), Duration::from_millis(200)).unwrap();
        create_private_dir(&store.store_dir(), false).unwrap();
        atomic_write(
            &store.store_dir().join(MANIFEST_FILE),
            &node_json_bytes(&new_preview_manifest(1, 1, "x", UNIX_EPOCH)),
        )
        .unwrap();
        atomic_write(&store.store_dir().join("coursework.json"), b"first").unwrap();
        let first = snapshot_daily(&store, UNIX_EPOCH).unwrap().unwrap();
        assert!(snapshot_daily(&store, UNIX_EPOCH).unwrap().is_none());
        for n in 1..=MAX_SNAPSHOTS {
            take(
                &store,
                "refresh",
                UNIX_EPOCH + std::time::Duration::from_secs(n as u64),
                &mut |_| {},
            )
            .unwrap();
        }
        assert_eq!(
            snapshot_before_refresh(&store, "synthetic refresh")
                .unwrap()
                .kind,
            "pre-refresh"
        );
        assert_eq!(list_snapshots(&store).unwrap().len(), MAX_SNAPSHOTS);
        assert!(!root(&store).join(first.id).exists());
        let latest = list_snapshots(&store).unwrap()[0].id.clone();
        atomic_write(&store.store_dir().join("coursework.json"), b"second").unwrap();
        restore_snapshot(&store, &latest).unwrap();
        assert_eq!(
            fs::read(store.store_dir().join("coursework.json")).unwrap(),
            b"first"
        );
        assert_eq!(fs::read_dir(store.backups_dir()).unwrap().count(), 1);
        assert_private_tree(&store.backups_dir());
        assert_private_tree(&root(&store));
    }
}
